name: 'Generate changelog'
description: 'Generate a changelog based on all commits of a repository'
inputs:
  token:
    description: Github token used to access the repository defined in the `repository` input.
    default: ${{ github.token }}
  repository:
    description: The owner and repository name (`owner/repository`).
    default: ${{ github.repository }}
  configLocation:
    description: Location of configuration file.
    default: changelog-configuration.json
  
outputs:
  changelog:
    description: 'The changelog generated'
runs:
  using: docker
  image: Dockerfile
