on: [push]

jobs:
  generator:
    runs-on: ubuntu-latest
    name: Generate changelog
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
#       - name: Use Node.js ${{ matrix.node-version }}
#         uses: actions/setup-node@v2
      
      - name: Install dependencies
        run: yarn install
      
      - name: Generate changelog
        uses: ./
        id: auto_changelog

      - name: Get the output time
        run: echo "${{ steps.auto_changelog.outputs.changelog }}"
